### ISSUE TITLE
[TODO] What is left to be done? (For Release 1.0)

### ISSUE THREAD

**Issue by kennyvv** [NiclasOlofsson/MiNET#18]
Just a small list of stuff we have to do. (incomplete, additional info may be added later)

Important:

- [x] Resend NAK's
- [x] PVP Damage calculations (We have to care about armor...)
- [ ] Block Data (FuelEfficiency, Durability, Metadata)
- [ ] Item Data (FuelEfficiency, MetaData, ItemType, ItemMaterial)

Extra:
- [ ] Biomes 
- [ ] Mob AI

If you guys find anything more to add, please tell me.
Also, if you finished something please open a pull request and tell us. I'll change it here.

**Comment by tonibm19** [comment]
Mobs?
Pc interoperability? :P

**Comment by NiclasOlofsson** [comment]
Not on the first release ;-)

**Comment by kennyvv** [comment]
@tonibm19 Yes. Mobs and PC Interoperability are things that would be awesome to have. However, currently i don't feel like this is a priority. Maybe in 1.1 or something like that. However, for the pc interoperability i made a plugin. Which is work in progress. and doesn't fully work anymore since the api changes. I will however upload a 'working' one soon. https://github.com/MiNET-Plugins/MiNET-PC

**Comment by vvzar** [comment]
What about server commands? /help i.e.

**Comment by FDKPIBC** [comment]
@vvzar u can do it with a plugin,and i'm writing it.

**Comment by kennyvv** [comment]
@vvzar I think this is a good idea, we were adding some already. However i'm not sure if this is really something that has priority for 1.0. I will discuss this with Niclas.

**Comment by vvzar** [comment]
What benefits server takes from my host with 40 cores and 128Gb RAM? 
Multi threading?  Can it use as much amount of ram and many threads as I figure in server properties?
And is any specs for configuration i.e. config file examples?

**Comment by NiclasOlofsson** [comment]
@vvzar I'm not sure if that is a question or if you are asking for a feature of sorts.

MiNET will automatically use the number of cores as you make available to it. It has the capactity to go full 100% on the CPU (and that is a feature), meaning it will use it to the max. It will also use hyperthreading to increase throughput, but at the cost of latency. But with 40 cores, that wouldn't be a problem.
Unfortunately it will not use your 128Gb RAM. I haven't been able to make it above 120-130mb yet. So you might want to give that RAM away for charity.
It should be noted that one of the most important pieces of hardware for scaleability is the network cards for a server like this. A bad network card will force MiNET to use kernel time, a good one will offload the kernel. So, since it is written the way it is, it should also use benefit to the max from good quality on the network hardware.

Yeah, i could do settings for this, but it's not my intention since you can sett affinitiy for a process external to the process. RAM settings, i might do that later.

And now, we just need to find someone that actually want to try this on "40 cores".

**Comment by vvzar** [comment]
I can try this. I have free power in my cluster. And can make vm with linux or windows for testing. but how  i can start simulation for server at high load mode?

**Comment by NiclasOlofsson** [comment]
In the solution there is a load simulator called "service killer" that can be used. It needs some code configuration to work, so you need to plan the tests a bit. Usually you just start the server, and then start a simulator with 1000 players in each simulator. Then start more simulators until it breaks.

**Comment by kennyvv** [comment]
Seems old and incorrect.
