### ISSUE TITLE
RandomAltThing's TODO List

### ISSUE THREAD

**Issue by RandomAltThing** [NiclasOlofsson/MiNET#40]
This is a list of things in which I will implement as I learn more C#.

- [x] Add grass path block
- [x] Fix death messages
- [ ] Add more client messages
- [ ] Work some more on plugins
- [ ] Implementing blocks like snow layer and ice. (Working on)

And also just a quick question: hoe can we add items to creative inventory?

**Comment by NiclasOlofsson** [comment]
As i said, it's not a forum.

**Comment by RandomAltThing** [comment]
*cough* https://github.com/NiclasOlofsson/MiNET/issues/18

**Comment by NiclasOlofsson** [comment]
Hmm "And also just a quick question: hoe can we add items to creative inventory?"

**Comment by RandomAltThing** [comment]
Oh I thought you were talking about the TODO list.

**Comment by PEMapModder** [comment]
@RandomAltThing the issue tracker is for tracking issues related to the repository. Put the TODO list in your personal agenda. This is not your Google Keep page.

Even collaborators of the project shouldn't be doing this here, much less you aren't.
